In [18]:
import numpy as np
from load import load_data
from convert import convert
from pmc2 import *


In [19]:
data = load_data(7)
d = convert(data)

In [20]:
print(d['C'][:,3])
print(d['E'][:,3])

[ 33.3  74.8 106.1 130.4 153.3 172.9 211.8]
[]


In [21]:
C_index = d['pC'].size
E_index = d['pE'].size
if d['pC'].size == 0:
    bpE_last = 400 
elif d['pC'].size != 0:
    bpC_last = int(d['pC'][C_index-1])
if d['pE'].size == 0:
    bpE_last = 400 
elif d['pE'].size != 0:
    bpE_last = int(d['pE'][E_index-1])
#print(bpC_last)
#print(bpE_last)
nb_comb = int(len(range(0,bpE_last,5))*len(range(0,bpC_last,5)));
#print(nb_comb)

In [22]:
#error_stored = np.zeros(nb_comb//1)
#bp_stored = np.zeros((nb_comb//1,2))
bp_couple = np.zeros((nb_comb//1,2))
mean_error = []
a=0
for i in range(0,bpC_last,5):
    for j in range(0,bpE_last,5):
        bp_couple[a,0] = i
        bp_couple[a,1] = j
        P1, P2 = create_P1_and_P2(data,i,j)
        P1_coeff = np.transpose(get_plane_normal(P1,1,'x'))
        P2_coeff = np.transpose(get_plane_normal(P2,1,'x'))
        sP1 = np.dot(np.transpose(P1.sig123),P1_coeff)
        sP2 = np.dot(np.transpose(P2.sig123),P2_coeff)
        errP1 = 1-sP1
        errP2 = 1-sP2
        sumP1 = 0
        sumP2 = 0
        for err in errP1:
            sumP1 += err
        for err in errP2:
            sumP2 += err
        mean_error.append((sumP1 + sumP2)/(len(errP1)+len(errP2)))
        #print(mean_error[a])
        a=a+1
        
mean_error = np.array(mean_error)

In [23]:
bp_couple

array([[  0.,   0.],
       [  0.,   5.],
       [  0.,  10.],
       ...,
       [210., 385.],
       [210., 390.],
       [210., 395.]])

In [24]:
mean_error

array([4.36461839, 4.36461839, 4.36461839, ..., 4.03891977, 4.03891977,
       4.03891977])