In [1]:
import numpy as np
from load import load_data
from convert import convert
from math import pi, sqrt
from numpy import sin, tan ,cos
import math

In [2]:
#%matplotlib widget
#%matplotlib inline
#%matplotlib qt
import matplotlib.pyplot as plt
import matplotlib

from matplotlib.backends.backend_pgf import FigureCanvasPgf
matplotlib.backend_bases.register_backend('pdf', FigureCanvasPgf)

In [3]:
def get_C(data):
    return data[data[:,5] == 0]
def get_E(data):
    return data[data[:,5] == 60]
def get_o(data):
    return data[np.logical_and(data[:,5] != 60 , data[:,5] != 0)]

def get_p(data):
    return data[:,3]
def get_q(data):
    return data[:,4]
def get_t(data):
    return data[:,5]

In [4]:
import pmc2

In [5]:
data = load_data(9)
d = convert(data)

In [6]:
data

array([[ 62.8,   0. ,   0. ,  20.9,  62.8,   0. ],
       [121.1,  10. ,  10. ,  47. , 111.1,   0. ],
       [135.4,  18.1,  10. ,  54.5, 121.6,   3.3],
       [137.6,  38.6,  10. ,  62.1, 115.9,  12.3],
       [145.2,  58.1,  10. ,  71.1, 118.7,  20.5],
       [154. ,  77.5,  10. ,  80.5, 124.8,  27.9],
       [129.7,  97. ,  10. ,  78.9, 107.2,  44.7],
       [141.8, 108.9,  10. ,  86.9, 118.8,  46.1],
       [221.3,  40. ,  40. , 100.4, 181.3,   0. ],
       [237.7,  78.4,  40. , 118.7, 181.5,  10.6],
       [239.8, 119.5,  40. , 133.1, 174.2,  23.3],
       [268.3, 157.3,  40. , 155.2, 197.7,  30.9],
       [234. , 199.5,  40. , 157.8, 179.3,  50.4],
       [218.6, 218.6,  40. , 159. , 178.6,  60. ],
       [271.9,  60. ,  60. , 130.6, 211.9,   0. ],
       [286.1,  89.1,  60. , 145.1, 213. ,   6.8],
       [295.9, 119.4,  60. , 158.4, 212.6,  14. ],
       [288.1, 148.6,  60. , 165.6, 199.2,  22.6],
       [283.6, 178.8,  60. , 174.2, 193.8,  32.1],
       [281.4, 209.1,  60. , 18

# Input

- bpC : CT Compression data Break Point in p-q plane 
- bpE : CT Extension data Break Point in p-q plane

In [7]:
bpC = 400 #CT Compression data Break Point in p-q plane
bpE = 150 #CT Extension data Break Point in p-q plane 

In [8]:
P1,P2 = pmc2.create_P1_and_P2(data,bpC,bpE)

[ 1.26378338 -1.22931457 77.09439478]
0.4666895990527434
[ 1.19523394 -0.69004668 53.61178889]
0.6652071410182365


In [11]:
P1.t

array([1.04719755, 1.04719755, 0.48694686, 0.78016218, 0.80459679,
       0.53930674, 0.87964594, 0.39444441, 0.56025069, 0.72082098,
       0.86393798, 0.47996554, 0.68765973, 0.91106187])

In [11]:
import pmc
pmc.create_P1_and_P2(data,d,bpC,bpE)

[ 1.26378338 -1.22931457 77.09439478]
0.46668959905274326
[ 1.19523394 -0.69004668 53.61178889]
0.6652071410182355


({'data': array([[218.6, 218.6,  40. , 159. , 178.6,  60. ],
         [254.8, 254.8,  60. , 189.9, 194.8,  60. ],
         [135.4,  18.1,  10. ,  54.5, 121.6,   3.3],
         [137.6,  38.6,  10. ,  62.1, 115.9,  12.3],
         [145.2,  58.1,  10. ,  71.1, 118.7,  20.5],
         [154. ,  77.5,  10. ,  80.5, 124.8,  27.9],
         [129.7,  97. ,  10. ,  78.9, 107.2,  44.7],
         [141.8, 108.9,  10. ,  86.9, 118.8,  46.1],
         [237.7,  78.4,  40. , 118.7, 181.5,  10.6],
         [239.8, 119.5,  40. , 133.1, 174.2,  23.3],
         [268.3, 157.3,  40. , 155.2, 197.7,  30.9],
         [234. , 199.5,  40. , 157.8, 179.3,  50.4],
         [286.1,  89.1,  60. , 145.1, 213. ,   6.8],
         [295.9, 119.4,  60. , 158.4, 212.6,  14. ],
         [288.1, 148.6,  60. , 165.6, 199.2,  22.6],
         [283.6, 178.8,  60. , 174.2, 193.8,  32.1],
         [281.4, 209.1,  60. , 183.5, 195.5,  41.3],
         [282.4, 239.4,  60. , 193.9, 204.3,  49.5],
         [411.5, 147.2, 100. , 219.6, 

In [10]:
math.asin(3*be/(6*P['Vo']-be))

NameError: name 'be' is not defined